books/urls.py
from django.conf.urls import url
from books.views import *
from . import views

urlpatterns = [
    url(r'^$', BookList.as_view(), name='books'),
    url(r'^author/(?P<author_slug>[a-z0-9-]+)/$', views.book_list_by_author, name='books-author'),
    url(r'^(?P<pk>[0-9]+)/$', BookDetail.as_view(), name='book'),
    url(r'^add/$', BookAdd.as_view(), name='book-add'),
    url(r'^add/thanks$', BookAddThanks.as_view(), name='add-thanks'),
    url(r'^(?P<pk>[0-9]+)/delete/$', BookDelete.as_view(), name='book-delete'),
    url(r'^(?P<pk>[0-9]+)/edit/$', BookEdit.as_view(), name='book-edit'),
    url(r'^about/$', views.about, name='about'),
]

frontend/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^books/', include('books.urls', namespace='books'))
]

books/models.py
from django.db import models


class Book(models.Model):
    title = models.CharField(max_length=100, default="")
    title_slug = models.SlugField(max_length=100, default="")
    author = models.CharField(max_length=100, default="")
    author_slug = models.SlugField(max_length=100, default="")
    genre = models.CharField(max_length=100, unique=True)
    pub_year = models.IntegerField(default=0)
    summary = models.TextField(default="")
    characters = models.TextField(default="")

    def __str__(self):
        return "%s - %s" % (self.title, self.author)

books/forms.py
from django import forms
from django.utils.text import slugify
from .models import Book
import datetime
now = datetime.datetime.now()


class BookForm(forms.ModelForm):
    title = forms.CharField(label='Title', max_length=100,
                            widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Title'}))
    author = forms.CharField(label='Author', max_length=100,
                             widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Author'}))
    author_slug = forms.SlugField(required=False, label='Slug', max_length=100,
                             widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Author'}))
    genre = forms.CharField(label='Genre', max_length=100,
                            widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Genre'}))
    pub_year = forms.IntegerField(label='Year of Publication',
                                  widget=forms.NumberInput(attrs={'class': 'form-control',
                                                                  'placeholder': 'Year of Publication'}))
    summary = forms.CharField(label='Summary', widget=forms.Textarea(attrs={'class': 'form-control',
                                                                                 'placeholder':
                                                                                 'What is this book about?...'}))
    characters = forms.CharField(label='Characters', widget=forms.Textarea(attrs={'class': 'form-control',
                                                                                'placeholder':
                                                                                'Who are the main characters of this '
                                                                                'book?...'}))

    class Meta:
        model = Book
        fields = ['title', 'author', 'genre', 'pub_year', 'summary', 'characters']

    def save(self):
        instance = super(BookForm, self).save(commit=False)
        instance.title_slug = slugify(instance.title)
        instance.author_slug = slugify(instance.author)
        instance.save()

        return instance

    def clean_pub_year(self):
        data = self.cleaned_data['pub_year']
        if data > now.year:
            raise forms.ValidationError("Year of Publication is not valid!")
        return data

books/views.py
from django.shortcuts import render, HttpResponse
from django.core.urlresolvers import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, TemplateView, DeleteView, UpdateView
from .models import Book
from .forms import BookForm


class BookList(ListView):
    model = Book
    template_name = 'books/book-list.html'
    context_object_name = 'books'
    paginate_by = 5


class BookListByAuthor(ListView):
    model = Book
    template_name = 'books/book-list_by_author.html'
    context_object_name = 'books'
    paginate_by = 5

    def get_queryset(self, author_slug):
        return Book.objects.filter(author_slug=author_slug)


def book_list_by_author(request, author_slug):
    books = Book.objects.filter(author_slug=author_slug)
    author = books[0].author

    return render(
        request,
        'books/book_list_by_author.html',
        context={'books': books, 'author': author}
    )


class BookDetail(DetailView):
    model = Book
    template_name = 'books/book-detail.html'


class BookAdd(CreateView):
    model = Book
    template_name = 'books/book-add.html'
    form_class = BookForm
    success_url = '/books/add/thanks'


class BookAddThanks(TemplateView):
    template_name = 'books/book-add-thanks.html'


class BookDelete(DeleteView):
    model = Book
    success_url = reverse_lazy('books:books')


class BookEdit(UpdateView):
    model = Book
    template_name = 'books/book-add.html'
    form_class = BookForm
    success_url = reverse_lazy('books:books')


def about(request):
    return render(request, 'books/about.html')

books/templates/base.html
<html lang="en">
<head>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    <!-- Popper JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="UTF-8">

    <title>
        {% block title %}
        {% endblock %}
    </title>
</head>
<body>

    <div class="container-fluid">
        <div class="row">
            <div class="col">
                <nav class="navbar navbar-expand-sm bg-light border border-top-0">
                    <a class="navbar-brand" href="{% url 'books:books' %}">
                        Books
                    </a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapse">
                        <span class="text-primary">☰</span>
                    </button>
                    <div class="collapse navbar-collapse" id="collapse">
                        <ul class="navbar-nav float-right">
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'books:books' %}">Home</a>
                            </li>
                            <li>
                                <a class="nav-link" href="#">About</a>
                            </li>
                            <li>
                                <a class="nav-link" href="#">Contact</a>
                            </li>
                        </ul>
                    </div>
                </nav>
            </div>
        </div>

        <div class="row mt-3">
            <div class="col">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb border bg-light">
                        {% block breadcrumb %}
                        {% endblock %}
                    </ol>
                </nav>
            </div>
        </div>
    </div>

{% block body %}
{% endblock %}
</body>
</html>

books/templates/books/about.html
{% extends 'base.html' %}

{% block title %}
About
{% endblock %}

{% block body %}
<h1>About</h1>
<p1>
    Books is a list of your own books!
</p1>
{% endblock %}

books/templates/books/book-add-thanks.html
{% extends 'base.html' %}

{% block title %}
Book Add Thanks
{% endblock %}

{% block breadcrumb %}
<li class="breadcrumb-item"><a href="{% url 'books:books'%}">Books</a></li>
<li class="breadcrumb-item"><a href="{% url 'books:book-add'%}">Add</a></li>
<li class="breadcrumb-item active" aria-current="page">Thanks</li>
{% endblock %}

{% block body %}
<div class="container-fluid">
    <br>
    <div class="row">
        <div class="col-12 col-sm-8 col-md-6 col-lg-5 col-xl-4">
            <div class="card">
                <div class="card-header">
                    <a class="card-link" data-toggle="collapse" href="#bookAddThanks">
                        Thanks!
                    </a>
                </div>
                <div id="bookAddThanks" class="collapse show">
                    <div class="card-body bg-light">
                        <p>
                            Thanks for adding a new Book!
                        </p>
                        <a class="btn btn-primary" href="{% url 'books:books'%}"><strong>↶</strong> Back to Homepage</a>
                        <a class="btn btn-primary" href="{% url 'books:book-add'%}"><strong>✚</strong> Add New Book</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

books/templates/books/book-add.html
{% extends 'base.html' %}

{% block title %}
Book Add
{% endblock %}

{% block breadcrumb %}
<li class="breadcrumb-item"><a href="{% url 'books:books'%}">Books</a></li>
<li class="breadcrumb-item active" aria-current="page">Add</li>
{% endblock %}

{% block body %}
<div class="container-fluid">
    <br>

    <form method="POST" class="form-horizontal" role="form">
    {% csrf_token %}

        <div class="row">
            <div class="col">
                {% if form.errors %}
                    <div class="alert alert-danger alert-dismissible fade show">
                        {{ form.errors }}
                        <a class="close" data-dismiss="alert">&times;</a>
                    </div><br>
                {% endif %}
            </div>
        </div>

        <div class="row">
            <div class="col">
                <div class="card">
                    <div class="card-header">
                        <a class="card-link" data-toggle="collapse" href="#options">
                            Options
                        </a>
                    </div>
                    <div id="options" class="collapse show">
                        <div class="card-body bg-light">
                            <div class="form-group">
                                <button type="submit" class="btn btn-primary">
                                    ✔ Save
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Row -->
        <div class="row">

            <!-- Book Details Short -->
            <div class="col-12 col-md-6 col-lg-5 col-xl-4 mt-3">

                <!-- Card -->
                <div class="card">
                    <div class="card-header">
                        <a class="card-link" data-toggle="collapse" href="#bookFormShort">
                            Add Book Short
                        </a>
                    </div>
                    <div id="bookFormShort" class="collapse show">
                        <div class="card-body bg-light">
                    <!--==================================  Title  ==================================-->
                            <div class="form-group">
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                        <label class="input-group-text" for="{{form.title.id_for_label}}">Title</label>
                                    </div>
                                    {{ form.title }}
                                </div>
                            </div>
                    <!--==================================  Author  ==================================-->
                            <div class="form-group">
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                        <label class="input-group-text" for="{{form.author.id_for_label}}">Author</label>
                                    </div>
                                    {{ form.author }}
                                </div>
                            </div>
                    <!--==================================  Genre  ==================================-->
                            <div class="form-group">
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                        <label class="input-group-text" for="{{form.genre.id_for_label}}">Genre</label>
                                    </div>
                                    {{ form.genre }}
                                </div>
                            </div>
                    <!--==================================  Year of Publication  ==================================-->
                            <div class="form-group">
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                        <label class="input-group-text" for="{{form.pub_year.id_for_label}}">Year of Publication</label>
                                    </div>
                                    {{ form.pub_year }}
                                </div>
                            </div>
                        </div>
                    </div>
                </div> <!-- Card -->

            </div> <!-- Book Details Short -->

            <!-- Book Details Long -->
            <div class="col-12 col-md-6 col-lg-7 col-xl-8 mt-3">
                <!-- Card -->
                <div class="card">
                    <div class="card-header">
                        <a class="card-link" data-toggle="collapse" href="#bookFormLong">
                            Add Book Long
                        </a>
                    </div>
                    <div id="bookFormLong" class="collapse show">
                        <div class="card-body bg-light">
                        <!--==================================  Summary  ==================================-->
                            <div class="form-group">
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                        <label class="input-group-text" for="{{form.summary.id_for_label}}">Summary</label>
                                    </div>
                                    {{ form.summary }}
                                </div>
                            </div>
                        <!--==================================  Characters  ==================================-->
                            <div class="form-group">
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                        <label class="input-group-text" for="{{form.characters.id_for_label}}">Characters</label>
                                    </div>
                                    {{ form.characters }}
                                </div>
                            </div>
                        </div>
                    </div>
                </div> <!-- Card -->
            </div> <!-- Book Details Long -->

        </div>

    </form>

    </div> <!-- Row -->
</div> <!-- Container-Fluid -->
{% endblock %}

books/templates/books/book-detail.html
{% extends 'base.html' %}

{% block title %}
{{ book.title }}
{% endblock %}

{% block breadcrumb %}
<li class="breadcrumb-item"><a href="{% url 'books:books'%}">Books</a></li>
<li class="breadcrumb-item active" aria-current="page">{{ book.title }}</li>
{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col">
            <div class="card">
                <div class="card-header">
                    <a class="card-link" data-toggle="collapse" href="#options">
                        Options
                    </a>
                </div>
                <div id="options" class="collapse show">
                    <div class="card-body bg-light">
                        <a class="btn btn-primary" href="{% url 'books:book-delete' book.id %}">Delete</a>
                        <a class="btn btn-primary" href="{% url 'books:book-edit' book.id %}">Edit</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Row -->
    <div class="row">

        <!-- Book Details Short -->
        <div class="col-12 col-md-6 col-lg-5 col-xl-4 mt-3">

            <!-- Card -->
            <div class="card">
                <div class="card-header">
                    <a class="card-link" data-toggle="collapse" href="#bookDetailsShort">
                        Short Details
                    </a>
                </div>
                <div id="bookDetailsShort" class="collapse show">
                    <div class="card-body bg-light">
                        <ul class="list-group">
                            <li class="list-group-item">Title: <span class="font-weight-bold">{{ book.title }}</span></li>
                            <li class="list-group-item">Author: <a href="{% url 'books:books-author' book.author_slug %}"><span class="font-weight-bold">{{ book.author }}</span></a></li>
                            <li class="list-group-item">Genre: <span class="font-weight-bold">{{ book.genre }}</span></li>
                            <li class="list-group-item">Year of Publication: <span class="font-weight-bold">{{ book.pub_year }}</span></li>
                        </ul>
                    </div>
                </div>
            </div> <!-- Card -->

        </div> <!-- Book Details Short -->

        <!-- Book Details Long -->
        <div class="col-12 col-md-6 col-lg-7 col-xl-8 mt-3">

            <!-- Card -->
            <div class="card">
                <div class="card-header">
                    <a class="card-link" data-toggle="collapse" href="#bookDetailsLong">
                        Long Details
                    </a>
                </div>
                <div id="bookDetailsLong" class="collapse show">
                    <div class="card-body bg-light">
                        <ul class="list-group">
                            <li class="list-group-item">
                                <strong>Summary: </strong>{{ book.summary }}
                            </li>
                            <li class="list-group-item">
                                <strong>Characters: </strong>{{ book.characters }}
                            </li>
                        </ul>
                    </div>
                </div>
            </div> <!-- Card -->

        </div> <!-- Book Details Long -->

    </div> <!-- Row -->
</div> <!-- Container-Fluid -->
{% endblock %}

books/templates/books/book-list.html
{% extends 'base.html' %}

{% block title %}
Books
{% endblock %}

{% block breadcrumb %}
<li class="breadcrumb-item active" aria-current="page">Books</li>
{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-12 col-sm-8 col-md-6 col-lg-5 col-xl-4">
            <div class="card">
                <div class="card-header">
                    <a class="card-link" data-toggle="collapse" href="#bookList">
                        Book List
                    </a>
                    <a class="btn btn-primary float-right" href="{% url 'books:book-add' %}"><strong>✚</strong> Add Book</a>
                </div>
                <div id="bookList" class="collapse show">
                    <div class="card-body bg-light">
                        {% if is_paginated %}
                            <ul class="pagination">
                                {% if page_obj.has_previous %}
                                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Prev</a></li>
                                {% else %}
                                    <li class="page-item disabled"><a class="page-link" href="#">Prev</a></li>
                                {% endif %}

                                {% for i in paginator.page_range %}
                                    {% if page_obj.number == i %}
                                        <li class="page-item active"><a class="page-link" href="#">{{ i }}</a></li>
                                    {% else %}
                                        <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                                    {% endif %}
                                {% endfor %}

                                {% if page_obj.has_next %}
                                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
                                {% else %}
                                    <li class="page-item disabled"><a class="page-link" href="#">Next</a></li>
                                {% endif %}
                            </ul>
                        {% endif %}
                        <div class="list-group">
                        {% for book in books %}
                            <!--<a class="list-group-item" href="{% url 'books:book' book.id %}">{{ book.title }}</a>-->
                            <button type="button" class="list-group-item btn btn-link bg-white text-left border" data-toggle="modal" data-target="#bookOptions">{{ book.title }}</button>
                            <div class="modal fade" id="bookOptions">
                                <div class="modal-dialog modal-dialog-centered">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h4 class="modal-title">{{ book.title }}</h4>
                                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                                        </div>
                                        <div class="modal-body">
                                            <a class="btn btn-primary" href="{% url 'books:book' book.id %}">View</a>
                                            <a class="btn btn-primary" href="{% url 'books:book-edit' book.id %}">Edit</a>
                                            <a class="btn btn-primary" href="{% url 'books:book-delete' book.id %}">Delete</a>
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% empty %}
                            <span class="list-group-item btn btn-link bg-white text-left border disabled">No books yet.</span>
                        {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

books/templates/books/book_confirm_delete.html
{% extends 'base.html' %}

{% block title %}
Book Delete Confirmation
{% endblock %}

{% block breadcrumb %}
<li class="breadcrumb-item"><a href="{% url 'books:books'%}">Books</a></li>
<li class="breadcrumb-item"><a href="{% url 'books:book' book.id %}">{{ book.title }}</a></li>
<li class="breadcrumb-item active" aria-current="page">Delete</li>
{% endblock %}

{% block body %}
<div class="container-fluid">
    <br>
    <div class="row">
        <div class="col-12 col-sm-8 col-md-6 col-lg-5 col-xl-4">
            <div class="card">
                <div class="card-header">
                    <a class="card-link" data-toggle="collapse" href="#bookDelete">
                        Are you sure?
                    </a>
                </div>
                <div id="bookDelete" class="collapse show">
                    <div class="card-body bg-light">
                        <form action="{{ request.path }}" method="post">
                            {% csrf_token %}
                            <p>Do you really want to delete <a href="{% url 'books:book' book.id %}"><strong><i>{{ book.title }}</i></strong></a>?</p>
                            <button type="submit" class="btn btn-primary">Delete</button>
                            <a class="btn btn-primary" href="{% url 'books:book' book.id %}"><strong>↶</strong> No, take me back</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

books/templates/books/book_list_by_author.html
{% extends 'base.html' %}

{% block title %}
{{ author }}
{% endblock %}

{% block breadcrumb %}
<li class="breadcrumb-item"><a href="{% url 'books:books' %}">Books</a></li>
<li class="breadcrumb-item"><a href="#">Author</a></li>
<li class="breadcrumb-item active" aria-current="page">{{ author }}</li>
{% endblock %}
{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-12 col-sm-8 col-md-6 col-lg-5 col-xl-4">
            <div class="card">
                <div class="card-header">
                    <a class="card-link" data-toggle="collapse" href="#bookListByAuthor">
                        {{ author }}'s Books
                    </a>
                </div>
                <div id="bookListByAuthor" class="collapse show">
                    <div class="card-body bg-light">
                        {% if is_paginated %}
                            <ul class="pagination">
                                {% if page_obj.has_previous %}
                                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Prev</a></li>
                                {% else %}
                                    <li class="page-item disabled"><a class="page-link" href="#">Prev</a></li>
                                {% endif %}

                                {% for i in paginator.page_range %}
                                    {% if page_obj.number == i %}
                                        <li class="page-item active"><a class="page-link" href="#">{{ i }}</a></li>
                                    {% else %}
                                        <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                                    {% endif %}
                                {% endfor %}

                                {% if page_obj.has_next %}
                                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
                                {% else %}
                                    <li class="page-item disabled"><a class="page-link" href="#">Next</a></li>
                                {% endif %}
                            </ul>
                        {% endif %}
                        <div class="list-group">
                        {% for book in books %}
                            <!--<a class="list-group-item" href="{% url 'books:book' book.id %}">{{ book.title }}</a>-->
                            <button type="button" class="list-group-item btn btn-link bg-white text-left border" data-toggle="modal" data-target="#bookOptions">{{ book.title }}</button>
                            <div class="modal fade" id="bookOptions">
                                <div class="modal-dialog modal-dialog-centered">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h4 class="modal-title">{{ book.title }}</h4>
                                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                                        </div>
                                        <div class="modal-body">
                                            <a class="btn btn-primary" href="{% url 'books:book' book.id %}">View</a>
                                            <a class="btn btn-primary" href="{% url 'books:book-edit' book.id %}">Edit</a>
                                            <a class="btn btn-primary" href="{% url 'books:book-delete' book.id %}">Delete</a>
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% empty %}
                            <span class="list-group-item btn btn-link bg-white text-left border disabled">No books yet.</span>
                        {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}